
[package]
name = "rigidbody"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier3d = { version = "*", features =  [ ] }
rapier3d-urdf = "0.3.0"

#[[bin]]
#  name = "rapier3d_example"
#  path = "./rapier3d_multijoint_example.rs"
