
[package]
name = "rust_autodiff"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier3d = { version = "*", features =  [ ] }

[[bin]]
  name = "rapier3d_example"
  path = "./rapier3d_multijoint_example.rs"
