
[package]
name = "rigidbody"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
nalgebra = "0.33.2"
parry3d = "0.17.4"
rapier3d = "0.22.0"
rapier3d-urdf = "0.3.0"
xurdf = "0.2.5"

#[[bin]]
#  name = "rapier3d_example"
#  path = "./rapier3d_multijoint_example.rs"
